name: CI-Hybrid

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
    types: [reopened, synchronize, opened]

permissions:
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    environment: CI
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Integration tests
        uses: ./.github/actions/integration-tests
        with:
          CF_API: ${{ secrets['CF_API'] }}
          CF_USERNAME: ${{ secrets['CF_USERNAME'] }}
          CF_PASSWORD: ${{ secrets['CF_PASSWORD'] }}
          CF_ORG: ${{ secrets['CF_ORG'] }}
          CF_SPACE: ${{ secrets['CF_SPACE'] }}
          NODE_VERSION: 22.x
