name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag (optional)"
        required: false
        type: choice
        default: "latest"
        options:
          - "latest"
          - "previous"
          - "beta"

permissions:
  contents: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npmjs:@cap-js/data-privacy
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Tests
        uses: ./.github/actions/tests
        with:
          TEST_SUITE: tests/
          CDS_VERSION: latest
          NODE_VERSION: 24.x

      - name: Get npm version
        run: npm -v
      - run: npm publish --access public --provenance --tag ${{ github.event.inputs.tag }}

      - name: Get Version
        id: get-version
        run: |
          echo "version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
      - name: Parse changelog
        id: parse-changelog
        uses: schwma/parse-changelog-action@69a9f9ab4cf2f2e736108ab41396fc3c55f65e40 # v1.0.0
        with:
          version: "${{ steps.get-version.outputs.version }}"
      - name: Create a GitHub release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          tag: "v${{ steps.get-version.outputs.version }}"
          body: "${{ steps.parse-changelog.outputs.body }}"
