name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag (optional)"
        required: false
        type: choice
        default: "latest"
        options:
          - "latest"
          - "previous"
          - "beta"

permissions:
  contents: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Tests
        uses: ./.github/actions/tests
        with:
          TEST_SUITE: tests/
          CDS_VERSION: latest
          NODE_VERSION: 24.x

      - name: Get Version
        id: get-version
        run: |
          echo "version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
      - name: Parse changelog
        id: parse-changelog
        uses: schwma/parse-changelog-action@v1.0.0
        with:
          version: '${{ steps.get-version.outputs.version }}'
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.20.0
        with:
          tag: 'v${{ steps.get-version.outputs.version }}'
          body: '${{ steps.parse-changelog.outputs.body }}'
      - name: Get npm version
        run: npm -v
      - run: npm publish --access public --provenance
