name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Running ${{ matrix.testSuite }} for CAP ${{ matrix.cds-version }} and node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
        cds-version: [latest]
        testSuite: [tests/csn-enhancements, tests/retention, tests/information, tests/build]
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Tests
        uses: ./.github/actions/tests
        with:
          TEST_SUITE: ${{ matrix.testSuite }}
          CDS_VERSION: ${{ matrix.cds-version }}
          NODE_VERSION: ${{ matrix.node-version }}
